### ISSUE TITLE
missing (or mismentioned) optional arguments in methods

### ISSUE THREAD

**Issue by AnliYang** [learn-co-curriculum/ruby-arguments-readme#27]
In the first paragraph of the final section of the lesson (titled "USING ARGUMENTS IN METHODS"), optional arguments (as opposed to required arguments) are mentioned: "Now that we know how to define a method with arguments, either required, optional, or both [...]"

I'm not sure if they're meant to be included in this lesson or not, but they seem to be missing (or I'm missing them).

**Comment by AnnJohn** [comment]
Thanks for catching that @AnliYang. It was a mistake on our part and optional arguments are covered in the subsequent lessons. We will update this lesson.
