### ISSUE TITLE
Current age is currently incorrect (Not relevant in the current year)

### ISSUE THREAD

**Issue by dwatring** [learn-co-curriculum/ruby-arguments-readme#34]
Because of the new year, perhaps this should be rewritten to accommodate the 2016 current year.

I submitted the pull request [HERE!](https://github.com/learn-co-students/intro-to-tdd-rspec-and-learn-002/pull/50)

Thank you.

**Comment by AnnJohn** [comment]
Hi @dwatring thanks! Made a note on your PR, but this actually should be fixed now.
