### ISSUE TITLE
Method body indentation

### ISSUE THREAD

**Issue by pletcher** [learn-co-curriculum/ruby-arguments-readme#38]
Method bodies are indented too many spaces -- we need to be consistent.

**Comment by PeterBell** [comment]
Not sure that's true - downloaded the code and it seems to be two spaces everywhere. Don't see a fix in the last 8 days, so I wonder if this is just a rendering issue? Just to be clear - what is the consistent rule? A single tab? Two spaces? This lab appears to use two spaces which doesn't seem unreasonable. LMK @pletcher

**Comment by pletcher** [comment]
Oh, you found one my grumpy notes-to-self :)

I'm referring to this:

<img width="932" alt="screen shot 2016-05-04 at 2 09 48 pm" src="https://cloud.githubusercontent.com/assets/2015049/15024193/e824a11a-1201-11e6-975e-9c36de5c77cc.png">

In an earlier lab, two spaces was mentioned as the rule (I think -- I can try to dig that up). I think in some cases there are two two-spaced tabs (like in the above) or four spaces?

**Comment by PeterBell** [comment]
Grumpiness gone :)
