### ISSUE TITLE
Unclear paragraph about  what considered bad style when a method takes an argument

### ISSUE THREAD

**Issue by callwin** [learn-co-curriculum/ruby-arguments-readme#40]
> A NOTE ON CALLING METHODS
> In the above examples, we're calling methods with parentheses, e.g., greeting('Sophie'). But you can also omit the parentheses: greeting 'Sophie'.
> When a method takes an argument, this is generally considered bad style, as it's a bit more difficult to understand what's going on ....

Second paragraph is unclear. Omitting the parentheses is bad style, but a method taking an argument is not.
Maybe it should be rewritten, like:

> In the above examples, we're calling methods with parentheses, e.g., `greeting('Sophie')`. 
> You can also omit the parentheses: `greeting 'Sophie'`, but it is generally considered bad style, as it's a bit more difficult to understand what's going on ....

**Comment by mendelB** [comment]
Thanks @callwin! We've fixed this
