### ISSUE TITLE
Video issue

### ISSUE THREAD

**Issue by symasson** [learn-co-curriculum/ruby-arguments-readme#44]
video is very blurry, making it impossible to read

**Comment by Joll59** [comment]
@symasson Sorry for the delayed response. The video was recorded in 720p, this might have been a connectivity issue. Please try rewatching the video and if the problem persists, check the video quality settings by clicking the gear icon and increasing the video quality if it is set lower than 720p. 

Closing issue for now. 

Thank you and happy coding!
