### ISSUE TITLE
Stating clearly the usage of arguments and parameters in Ruby

### ISSUE THREAD

**Issue by AaronSamuelJ** [learn-co-curriculum/ruby-arguments-readme#45]
I had a long debate on the difference between these two terms in Ruby with the tech coaches.  They said programmers decided to do away with the convention of using the terms separately.  They said that the terms are synonymous.  I agreed that they can be used casually so as not to confuse beginners but that there is a difference between them in meaning in regards to computer science.  None of the coaches would concede my point and made me feel like I was wrong even though the definitions are clearly delineated in computer science terminology.  I think it should be clearly stated in the lesson that arguments and parameters are going to be conjoined into just arguments for lack of confusion.  Thanks!

**Comment by cjbrock** [comment]
Hi Aaron,
I think there can be cause to use the two terms separately, but I think adding in more information about parameters versus arguments would add more complexity to a concept that is brand new to most students at this point. It could be unnecessarily confusing. We have a Computer Science track in our Full Stack Web Developer program that can be used to address more technical points such as this. Thank you for bringing up an interesting debate!
--Corinna
