### ISSUE TITLE
no examples found in introduction.rb

### ISSUE THREAD

**Issue by samk826** [learn-co-curriculum/ruby-arguments-readme#46]
♥ learn
An error occurred while loading spec_helper.
Failure/Error: require_relative "../lib/introduction.rb"
LoadError:
  cannot load such file -- /home/scruffy-generator-2805/method-arguments-lab-online-web-prework/lib/introduction.rb
# ./spec/spec_helper.rb:1:in `require_relative'
# ./spec/spec_helper.rb:1:in `<top (required)>'
An error occurred while loading ./spec/introduction_spec.rb.
Failure/Error: require_relative "../lib/introduction.rb"
LoadError:
  cannot load such file -- /home/scruffy-generator-2805/method-arguments-lab-online-web-prework/lib/introduction.rb
# ./spec/spec_helper.rb:1:in `require_relative'
# ./spec/spec_helper.rb:1:in `<top (required)>'
# ./spec/introduction_spec.rb:1:in `<top (required)>'
An error occurred while loading ./spec/introduction_spec.rb.
Failure/Error: require_relative "../lib/introduction.rb"
LoadError:
  cannot load such file -- /home/scruffy-generator-2805/method-arguments-lab-online-web-prework/lib/introduction.rb
# ./spec/spec_helper.rb:1:in `require_relative'
# ./spec/spec_helper.rb:1:in `<top (required)>'
# ./spec/introduction_spec.rb:1:in `<top (required)>'
No examples found.
No examples found.
Finished in 0.00044 seconds (files took 0.15655 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples
Finished in 0.00044 seconds (files took 0.15655 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples

**Comment by drakeltheryuujin** [comment]
Hi there @samk826,

I'm not sure what lesson this stack trace is referring to as this is a README and doesn't have any files to be tested. If this is meant for another lesson, please open this issue in the correct repo so it can be resolved.

Thanks! 💙
