### ISSUE TITLE
Potential "reference error" :)

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/ruby-arguments-readme#47]
This lesson seems to continually mistakenly refer to what I have come to understand as "parameters", using the word "arguments." 

As I have been taught, parameters are at method definition, and arguments are at method execution.

Am I mistaken?

**Comment by maxwellbenton** [comment]
Hi @m-cal,

Thank you for spotting this and providing feedback. You are correct that parameters are used to define methods, while arguments are what gets passed in when a method is called. We've updated this lesson's instructions to correctly use the two terms, which should resolve this issue.

Thank you for taking the time to provide this feedback and help improve our content for future students!
