### ISSUE TITLE
video

### ISSUE THREAD

**Issue by gennetteg** [learn-co-curriculum/ruby-arguments-readme#48]
the videos are getting messed up in fullscreen mode and I cant really see much when its not on fullscreen

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up there.

Thanks for contributing to the Flatiron School curriculum! 💙
