### ISSUE TITLE
Error in Methods and Arguments code (?)

### ISSUE THREAD

**Issue by dougtebay** [learn-co-curriculum/ruby-arguments-readme#6]
Hi, in your Intro to Ruby/Methods and Arguments tutorial (under "Optional Arguments with Default Values") you give an example of a method in which both arguments have default values: def count_from_to(start_of_range = 1, end_of_range = 100). You then give an example of the output when one argument is supplied--(count_from_to(10)--that shows a result of "1 ... 10". This got my attention because it seems to imply that Ruby automatically assumes the supplied "10" is for the 2nd argument (end_of_range) instead of the 1st. I tried running the code and got the result "10 ... 100" instead of "1 ... 10" which made me think the example might be a mistake. Just wanted to give you a heads up.

**Comment by AnnJohn** [comment]
@dougtebay Thanks for the report. Could you provide some screenshots to make the issue a little bit more clear?

**Comment by dougtebay** [comment]
Sure (note, in IRB I changed the end_of_range default value from 100 to 20 so the output wouldn't be so long):
![screen shot 2015-08-21 at 10 07 40 am](https://cloud.githubusercontent.com/assets/13855895/9410366/e4e25a30-47ed-11e5-8873-15cc132d0a07.png)
![screen shot 2015-08-21 at 10 17 09 am](https://cloud.githubusercontent.com/assets/13855895/9410373/ef362d22-47ed-11e5-8ee2-2458ffa07380.png)

**Comment by AnnJohn** [comment]
@dougtebay This is great and really clear. Thanks.

**Comment by SophieDeBenedetto** [comment]
Thanks @dougtebay, it should be fixed now!
